FROM openjdk:8 as builder

COPY ./app/ /app/
WORKDIR /app
RUN cd /app && ./gradlew build --full-stacktrace

FROM openjdk:alpine 
WORKDIR /app
COPY --from=builder /app/build/libs/uob-todo-app-0.1.0.jar .
COPY ./app/java_wrap.sh /java_wrap.sh
ENTRYPOINT ["/java_wrap.sh", "uob-todo-app-0.1.0.jar"]
